### ISSUE TITLE
Kanban Board Info

### ISSUE THREAD

**Issue by sameedmohsin28** [sameedmohsin28/Catalogue-of-my-things#31]
[Click here](https://github.com/sameedmohsin28/Catalogue-of-my-things/projects/1) to view the GitHub project.
There are three members in the team, the following are their names;
Team member 1: @sameedmohsin28
Team member 2: @federicaulzurrun
Team member 3: @Mylo16

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Group work ✔️ 
- Good implementations ✔️

## Required Changes ♻️
- [x] [REQUIRED] Good job so far! Please each card on the board should have a `descriptive` description of the task 🙏🏼 Kindly add description to these cards:
- #14,
- #21,
- #28 

![image](https://github.com/sameedmohsin28/Catalogue-of-my-things/assets/63915024/5104ae91-7da6-4bd9-89a6-4ee1e22e3560)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by abdulhamiid** [comment]
Hi Team 👋, 

## STATUS: APPROVED 😃

In my opinion, your project is complete! 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
